import = ["/home/htoopyae/.config/alacritty/colors.toml", "/home/htoopyae/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 84
lines = 24

[window.padding]
x = 10
y = 10
