#!/usr/bin/env zsh

# Folders that should link to ~/.config
CONFIG_FOLDERS="kitty starship"

# Folders that should link directly to home directory
HOME_FOLDERS="gitconfig tmux vim zsh"

DOT_FILES=$HOME/.dotfiles

pushd $DOT_FILES

for folder in $(echo $CONFIG_FOLDERS | sed "s/,/ /g")
do
    mkdir -p $HOME/.config/$folder

    echo "Linking $folder to $HOME/.config/$folder"
    stow -D -t $HOME/.config/$folder $folder
    stow -t $HOME/.config/$folder $folder
done

for folder in $(echo $HOME_FOLDERS | sed "s/,/ /g")
do
    echo "Linking $folder to $HOME"
    stow -D -t $HOME $folder
    stow -t $HOME $folder
done

popd
