#!/usr/bin/env zsh

STOW_FOLDERS="gitconfig,tmux,vim,zsh,kitty"

DOT_FILES=$HOME/.dotfiles

pushd $DOT_FILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    if [[ $folder == "kitty" ]]; then
        stow -D -t $HOME/.config/kitty $folder
        stow -t $HOME/.config/kitty $folder
    else
        stow -D $folder
        stow $folder
    fi
done
popd
